version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: notes-database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
  
  backend:
    build:
      context: .
    container_name: notes-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  database: